version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tango_api
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=tango
    depends_on:
      - postgres
    volumes:
      - .:/app  # 本機目錄掛載到容器的 /app 目錄，實現即時更新

  postgres:
    image: postgres:15
    container_name: tango_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: tango
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
